harborProject: harbor.lab.brianragazzi.com/tmc-sm
dnsZone: tmc.lab.brianragazzi.com
clusterIssuer: cloudflare-issuer
postgres:
  userPassword: admin
  maxConnections: 300
minio:
  username: root
  password: password123
contourEnvoy:
  serviceType: LoadBalancer
  #serviceAnnotations: # needed only when specifying load balancer controller specific config like preferred IP
  #  ako.vmware.com/load-balancer-ip: "10.20.10.100"
  # when using an auto-assigned IP instead of a preferred IP, please use the following key instead of the serviceAnnotations above
  # loadBalancerClass: local
authenticationType: ldap
oidc:
  issuerType: pinniped
  issuerURL: https://pinniped-supervisor.tmc.lab.brianragazzi.com/provider/pinniped
idpGroupRoles:
  admin: tmcadmins #these exist in AD
  member: tmcmembers
ldap:
  type: activedirectory
  host: "adc2.ragazzilab.com:636" #:3269"
  username: "CN=svc bind,OU=Service Accounts,DC=ragazzilab,DC=com"
  password: "VMware1!"
  domainName: "ragazzilab"
  userBaseDN: "DC=ragazzilab,DC=com"
  userSearchFilter: "(&(objectClass=person)(userPrincipalName={}))"
  userSearchAttributeUsername: userPrincipalName #sAMAccountName
  groupBaseDN: "DC=ragazzilab,DC=com"
  groupSearchFilter: (&(objectClass=group)(member={})(|(CN=tmcmembers)(CN=tmcadmins))) #"(&(objectClass=group)(member={}))"
  rootCA: |-
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIQEOXQ9zrq+6lIbFlj1/ZZzjANBgkqhkiG9w0BAQ0FADBP
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRowGAYKCZImiZPyLGQBGRYKcmFnYXp6aWxh
    YjEcMBoGA1UEAxMTcmFnYXp6aWxhYi1BRERTMS1DQTAeFw0yMTA3MDEwMDA0NDla
    Fw0zMTA3MDEwMDE0NDhaME8xEzARBgoJkiaJk/IsZAEZFgNjb20xGjAYBgoJkiaJ
    k/IsZAEZFgpyYWdhenppbGFiMRwwGgYDVQQDExNyYWdhenppbGFiLUFERFMxLUNB
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6Zhkf0Nz6vXDRjv3Xx3+
    BLR/P6ptojhHQfM7IXmDx2Y6IzxpuipG+DIudsxeJGoHFm9zvtWIhKMAs8/UzPsI
    PXKPal+DMudPKRIhAoVB6uk1ipfzWxE+E8UoksMSdMLnh0KDaaNuoyCZrm6OYBre
    wpoHpty0KN5zxEIInfpGEGnc+bdQNCB/7MZdhNIipWgueHdwyDqIeFm8Gx3Myv0P
    b0ucweO0ayDflnoEz+TESbtAnLu8a88rzZ/eSyuT8rFAdcAzzLrENL7MNxoczH2Z
    qdtvRG+MSJ04s7h8wI8e7l2npl9NTgBGzUaeR4+OqHYmnvqBVVXQbltvgosFSEap
    aQIDAQABo2kwZzATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNVHQ8BAf8EBAMCAYYw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU/O+fv5NTXrC+zA77JDMCHOG2Cf4w
    EAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQENBQADggEBAFrn29A9GwAOsSya
    YDjDyrQ82oTxYbP7EFdVoixbSeSE8+G6SPmNGOOYF/o4gobrWf/OUNGLGpVdoGGu
    Q0HCZp5GJqbxMhyeushTWHEQGhaaxX/hd4KtPZjgEJJqVLoMM+4j+uSr5os3Kgr8
    jP6AwRVcCnOzL5HIvQSl4WEWdzw42FlLn+bUUGt3l9nnrxaIeqrRrhDem0fXl3Bp
    D/25HD5xz4MsaN5SZ6xuBc9c9P1qMQ2tTdurqlboAwGNRcY5WYytsj3zHYIlU11h
    hFs8tYWQQjmIYkIB0PiRjI8xN7BhijAafi6H3CPLQ8iOdJm5AJ5C7ioJlOBfKX90
    lORZ8As=
    -----END CERTIFICATE-----
# alertmanager: # needed only if you want to turn on alerting
#   criticalAlertReceiver:
#     slack_configs:
#     - send_resolved: false
#       api_url: https://hooks.slack.com/services/...
#       channel: '#<slack-channel-name>'
telemetry:
  ceipOptIn: false
  eanNumber: ean-not-specified # if EAN is available
  ceipAgreement: false
size: small
#certificateImport: true
trustedCAs:
  custom-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFtzCCA5+gAwIBAgIUGIbHIzm/yaKP2OFAiwc3Kg0zYjIwDQYJKoZIhvcNAQEN
    BQAwazELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1TMRAwDgYDVQQHDAdNYWRpc29u
    MRAwDgYDVQQKDAdSYWdhenppMQwwCgYDVQQLDANMYWIxHTAbBgNVBAMMFCoudG1j
    LnJhZ2F6emlsYWIuY29tMB4XDTI0MDUxMTEzNDkzOVoXDTM0MDUwOTEzNDkzOVow
    azELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1TMRAwDgYDVQQHDAdNYWRpc29uMRAw
    DgYDVQQKDAdSYWdhenppMQwwCgYDVQQLDANMYWIxHTAbBgNVBAMMFCoudG1jLnJh
    Z2F6emlsYWIuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0Has
    RumKshjyXH3fuItwKmo8O2skvPTTWTeP1MuPAmxC1GCcKNZFxlkihkCN+DO51YvH
    cer25b3u9SbrE+wAo4rm8wwujgUE5IkJvqZZI3HdjhIha6HYfWbWJ1wuw5NjKIaD
    PA/Prem5qZeBew2zLUwIq5tKQAgjvNEsD1DdniHZVfQykainwyX6Lnn3rxVFL9oi
    EVh+sa7Mia1X8FZkaQwqvVMb8uQutXnFhYngLNw6o39oCVKf0P9Puv8ZrWCZfJmt
    lZ1oJ4oheGhrLqnXzyamU688xQc6UbiZallOGOy6a/GYerTfzwUy8Ql0U/+uXxAw
    uGBbK5++vVoQo+PumQMWSC1ZI7XjiRlhU8ziv9rwv+QKfGWJtFXYLS2KsE1ciunj
    Y1AfEeKb/Uw72GTqZkzeQkqxRHW9HUJAPUhoKbWIaJn1/h7rHI9RFf5ncvv7obxf
    kshv5yp2zHBKKkr+LfEknN+Rv8lR+pbfCzx7AN/eDHMfzAoh2BlhIc+O5T1NwWLn
    z4fLr3RXR8CgxPAAeiluD9kQuCdHjbsUA5urxU9sbCmiOYdi7iiXLRWIExLcjC3g
    IdFK0SrcFD8dqAFAS+A+BdGUKp71wfrgG7MtdWsL+W8lBVXj/gFWsFDFqyBXcrOF
    tNJGX4KV+CEbLpXlG1kBWRgVwiFdFI9D2cO7UQUCAwEAAaNTMFEwHQYDVR0OBBYE
    FGNclwlnkuHQjGnisFYDEZBtdfmdMB8GA1UdIwQYMBaAFGNclwlnkuHQjGnisFYD
    EZBtdfmdMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQENBQADggIBAD3N5UB2
    UtCSfWa5kjW62RJ0EA8d3kj1Omaz4TOlVKtSp3kL8FfP6r7lkZoQtJmpsPFlXNOI
    m4KZgZj9bqahPFxVol+myJRq6uJwYix2zhB7vE2K3blZOynRbiq43MViAkyYHI5z
    I5lcqr7VwCFXP0ZI1HP4yWn8fEWIutjwB+/EYbgNIDdouAOopasJID4Gcfo8yCXm
    n9kiB+g6mhV69wkNTFAaIoZD6euwtT7Yuu+a0ZGKrj8tlZ+OhoRfOCOETlwnFKwK
    IGSrDqBrueYtMLGAxuhWClngMrhlSwlkmBEntNWDlqhJgC7p97Vy30r5Rz8C9Ux0
    CF26i7vaJOwRGMBiMDOFKZ14+oZK0nkAjg5IVYQduukz6/e9fdsZP+8k3/oBAmUz
    IeqY4J41jFfhr/1JFs2XmjitKmpisnZHJnyb3r33JqR6iBmj7gx9PY+0lPZIwmdD
    liPbzgmlcLMdLBfNnM3ggmddWWsy984yDuGDeMWz/cBURSYBf6X1l/iTBpsF4azb
    oii/dN4rY90iYwVmRyxRKnwRiBBiGSfHybsDixaGQTJOcDBiJ9lU82K3vTHnxE8V
    xz1Iy+Ace29HN7rYAlVBS6r2O6UpOi6IOiZHLm88rEcuUwnEJdJsdNuaRABYOcnX
    isP2Bh+YOwkJMqDVS6LA0kb2WQe5tiivNR0T
    -----END CERTIFICATE-----
  isrg-root.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----
  rootCA: |-
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIQEOXQ9zrq+6lIbFlj1/ZZzjANBgkqhkiG9w0BAQ0FADBP
    MRMwEQYKCZImiZPyLGQBGRYDY29tMRowGAYKCZImiZPyLGQBGRYKcmFnYXp6aWxh
    YjEcMBoGA1UEAxMTcmFnYXp6aWxhYi1BRERTMS1DQTAeFw0yMTA3MDEwMDA0NDla
    Fw0zMTA3MDEwMDE0NDhaME8xEzARBgoJkiaJk/IsZAEZFgNjb20xGjAYBgoJkiaJ
    k/IsZAEZFgpyYWdhenppbGFiMRwwGgYDVQQDExNyYWdhenppbGFiLUFERFMxLUNB
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6Zhkf0Nz6vXDRjv3Xx3+
    BLR/P6ptojhHQfM7IXmDx2Y6IzxpuipG+DIudsxeJGoHFm9zvtWIhKMAs8/UzPsI
    PXKPal+DMudPKRIhAoVB6uk1ipfzWxE+E8UoksMSdMLnh0KDaaNuoyCZrm6OYBre
    wpoHpty0KN5zxEIInfpGEGnc+bdQNCB/7MZdhNIipWgueHdwyDqIeFm8Gx3Myv0P
    b0ucweO0ayDflnoEz+TESbtAnLu8a88rzZ/eSyuT8rFAdcAzzLrENL7MNxoczH2Z
    qdtvRG+MSJ04s7h8wI8e7l2npl9NTgBGzUaeR4+OqHYmnvqBVVXQbltvgosFSEap
    aQIDAQABo2kwZzATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNVHQ8BAf8EBAMCAYYw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU/O+fv5NTXrC+zA77JDMCHOG2Cf4w
    EAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQENBQADggEBAFrn29A9GwAOsSya
    YDjDyrQ82oTxYbP7EFdVoixbSeSE8+G6SPmNGOOYF/o4gobrWf/OUNGLGpVdoGGu
    Q0HCZp5GJqbxMhyeushTWHEQGhaaxX/hd4KtPZjgEJJqVLoMM+4j+uSr5os3Kgr8
    jP6AwRVcCnOzL5HIvQSl4WEWdzw42FlLn+bUUGt3l9nnrxaIeqrRrhDem0fXl3Bp
    D/25HD5xz4MsaN5SZ6xuBc9c9P1qMQ2tTdurqlboAwGNRcY5WYytsj3zHYIlU11h
    hFs8tYWQQjmIYkIB0PiRjI8xN7BhijAafi6H3CPLQ8iOdJm5AJ5C7ioJlOBfKX90
    lORZ8As=
    -----END CERTIFICATE-----
