apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  secretName: testcert
  renewBefore: 240h
  dnsNames:
  - 'test.tmc.lab.brianragazzi.com'
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
